name: Add Link to Weekly Digest
on:
  workflow_dispatch:
    inputs:
      link:
        description: 'Enter the link'
        required: true
      title:
        description: 'Enter the title'
        required: false
      description:
        description: 'Enter the description'
        required: false
jobs:
  add-link-to-week-digest:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: create env file
        run: |
          touch .env
          echo GH_TOKEN=${{ secrets.GH_TOKEN }} >> .env
          echo LINK=${{ github.event.inputs.link }} >> .env
          echo TITLE="${{ github.event.inputs.title }}" >> .env
          echo DESCRIPTION="${{ github.event.inputs.description }}" >> .env
      - name: 🏗 Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Make sure issue for current week is created
        run: |
          pnpm create-week-digest

      - name: Add link
        run: |
          pnpm add-link-to-week-digest
